#!/bin/bash

# ========================================
# Bot Credentials Quick Reference
# ========================================

echo "📋 Bot Credentials from Azure Portal Screenshot:"
echo ""
echo "✅ BOT_ID (Microsoft App ID):"
echo "   <YOUR_BOT_ID_HERE>"
echo ""
echo "✅ BOT_TENANT_ID (App Tenant ID):"
echo "   <YOUR_TENANT_ID_HERE>"
echo ""
echo "⚠️  BOT_PASSWORD (Client Secret):"
echo "   This is NOT visible in the screenshot."
echo "   You need to get it from Azure Portal:"
echo ""
echo "   Option 1: If you have it saved somewhere"
echo "   ----------------------------------------"
echo "   Use the existing client secret value you created when setting up the bot."
echo ""
echo "   Option 2: Create a new client secret"
echo "   -------------------------------------"
echo "   1. Go to: https://portal.azure.com"
echo "   2. Navigate to: Microsoft Entra ID > App registrations"
echo "   3. Find app: <YOUR_BOT_ID_HERE>"
echo "   4. Go to: Certificates & secrets > Client secrets"
echo "   5. Click: + New client secret"
echo "   6. Add description: 'Teams Bot for Container Apps'"
echo "   7. Set expiration: 24 months (recommended)"
echo "   8. Click: Add"
echo "   9. IMMEDIATELY COPY the 'Value' (you can't see it again!)"
echo ""
echo "   Direct link to App Registration:"
echo "   https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Credentials/appId/<YOUR_BOT_ID_HERE>"
echo ""
echo "=========================================="
echo ""
echo "📝 After you get the client secret, edit deploy_aca_command.sh:"
echo ""
echo "   BOT_ID=\"<YOUR_BOT_ID_HERE>\""
echo "   BOT_PASSWORD=\"<paste-your-client-secret-here>\""
echo "   BOT_TENANT_ID=\"<YOUR_TENANT_ID_HERE>\""
echo ""
