name: Build and Deploy to original pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ACR_NAME: aqnewacr007
  ACR_LOGIN_SERVER: aqnewacr007.azurecr.io
  IMAGE_NAME: nl2sql-streamlit-app
  RESOURCE_GROUP: AI-FOUNDRY-RG
  CONTAINERAPP_NAME: nl2sql-streamlit-app
  CONTAINERAPP_ENV: nl2sql-streamlit-app-env
  REGION: swedencentral

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest .
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az containerapp update \
              --name $CONTAINERAPP_NAME \
              --resource-group $RESOURCE_GROUP \
              --image $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
